apiVersion: apps/v1
kind: Deployment
metadata:
  name: monblog-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monblog
  template:
    metadata:
      labels:
        app: monblog
    spec:
      containers:
      - name: php-app
        image: amcs25/monblog:latest # VÃ©rifie bien ce nom sur Docker Hub
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_NAME
          value: "monblog"
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          value: "root"