apiVersion: apps/v1
kind: Deployment
metadata:
  name: monblog-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monblog
  template:
    metadata:
      labels:
        app: monblog
    spec:
      containers:
      - name: php-app
        image: DOCKERHUB/monblog:latest
        ports:
        - containerPort: 80